export const SHANNON_TOOLS = new Set([
  "shannon_exec",
  "shannon_docker_init",
  "shannon_docker_cleanup",
  "shannon_recon",
  "shannon_vuln_discovery",
  "shannon_exploit",
  "shannon_report",
  "shannon_browser",
  "shannon_idor_test",
  "shannon_js_analyze",
  "shannon_headers_audit",
  "shannon_param_fuzz",
  "shannon_api_fuzzer",
  "shannon_tls_scan",
  "shannon_crawler",
  "shannon_rate_limit_test",
  "shannon_subdomain_takeover",
  "shannon_upload_test",
  "shannon_auth_session",
  "shannon_file_extract",
])

export const TOOL_PHASES: Record<string, string> = {
  shannon_docker_init: "INIT",
  shannon_docker_cleanup: "CLEANUP",
  shannon_recon: "Reconnaissance",
  shannon_vuln_discovery: "Vulnerability Discovery",
  shannon_exploit: "Exploitation",
  shannon_report: "Report",
  shannon_browser: "Browser Testing",
  shannon_idor_test: "IDOR Testing",
  shannon_js_analyze: "JS Analysis",
  shannon_headers_audit: "Headers Audit",
  shannon_param_fuzz: "Parameter Fuzzing",
  shannon_api_fuzzer: "API Fuzzing",
  shannon_tls_scan: "TLS Scan",
  shannon_crawler: "Crawling",
  shannon_rate_limit_test: "Rate Limit Testing",
  shannon_subdomain_takeover: "Subdomain Takeover",
  shannon_upload_test: "Upload Testing",
  shannon_auth_session: "Auth Session",
  shannon_exec: "Command Execution",
  shannon_file_extract: "File Extraction",
}

export const PROGRESS_PREFIX = "\n[Shannon Progress] "
